CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 3
PRINT_FREQ: 10

DATASET:
  DATASET: gtav
  ROOT: data/
  TEST_SET: 'list/gtav/test.lst'
  TRAIN_SET: 'list/gtav/trainval.lst'
  NUM_CLASSES: 35
MODEL:
  NAME: sanet
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/cityscapes/sanet_S.pt"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  ExpName: 'SANet_GTAV_S'
  IMAGE_SIZE:
  - 1024
  - 1024
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 12
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 150
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.001
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: true
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 2048
  - 1024
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 6
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: 'pretrained_models/gtav/sanet_s_cityscapes.pt'
  OUTPUT_INDEX: 1
