CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 3
PRINT_FREQ: 10

DATASET:
  DATASET: camvid
  ROOT: /home/ubuntu/Projects/PIDNet/data/
#  ROOT: data/
  TEST_SET: 'list/camvid/test.lst'
  TRAIN_SET: 'list/camvid/trainval.lst'
  NUM_CLASSES: 11
MODEL:
  NAME: sanet
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/cityscapes/sanet_M.pt"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  ExpName: 'SANet_M_学习率0.001_12'
  IMAGE_SIZE:
  - 960
  - 720
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 12
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 150
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.001
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: true
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 960
  - 720
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
